version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/application"
    update_schedule: "daily"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/library"
    update_schedule: "daily"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"
